---
# tasks file for sbaerlocher.anydesk

- name: 'windows : create tools folder'
  win_file:
    path: '{{ anydesk_tools_directory }}'
    state: directory

- name: 'windows : download AnyDesk'
  win_get_url:
    url: '{{ anydesk_download_url }}'
    dest: '{{ anydesk_tools_directory }}\\{{ anydesk_binary_nane }}'
    proxy_url: '{{ anydesk_proxy }}'
    validate_certs: '{{ anydesk_validate_certs }}'

- name: 'windows : shortcuts for support'
  win_shortcut:
    desc: 'AnyDesk QuickSupport'
    src: '{{ anydesk_exe_path }}'
    dest: '%Public%\\Desktop\\Support.lnk'
